name = "jh-portfolio"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "CHAT_CACHE"
id = "8f98a62ef5654743b99ffd4502f2bb2b"
preview_id = "8f98a62ef5654743b99ffd4502f2bb2b"
