export const webTiers = [
  {
    tier: "Starter",
    name: "Landing Page",
    desc: "A sharp, mobile-ready landing page that makes your business look the part. Fast to ship, built to convert.",
    currency: "$",
    amount: "299",
    originalAmount: "399",
    period: "/ project",
    note: "One-time · Delivered in 5–7 days",
    features: [
      { label: "Up to 5 sections", dim: false },
      { label: "Mobile responsive", dim: false },
      { label: "Contact form", dim: false },
      { label: "Basic SEO setup", dim: false },
      { label: "CMS / blog", dim: true },
      { label: "Backend / database", dim: true },
    ],
    cta: "Get a Quote",
    featured: false,
    delay: 1,
  },
  {
    tier: "Growth",
    name: "Full Website",
    desc: "A full website with CMS — publish content, rank on search, and manage pages without touching code.",
    currency: "$",
    amount: "799",
    originalAmount: "999",
    period: "/ project",
    note: "One-time · Delivered in 2–3 weeks",
    features: [
      { label: "Up to 10 pages", dim: false },
      { label: "Mobile responsive", dim: false },
      { label: "CMS integration", dim: false },
      { label: "Blog / portfolio", dim: false },
      { label: "Custom animations", dim: false },
      { label: "SEO + analytics", dim: false },
    ],
    cta: "Get a Quote",
    featured: true,
    delay: 2,
  },
  {
    tier: "Custom",
    name: "Web App",
    desc: "A real web application: auth, database, dashboards, and custom logic. Built for businesses that have outgrown templates.",
    currency: "$",
    amount: "1,500",
    originalAmount: null,
    period: "+ / project",
    note: "Custom quote · Timeline by scope",
    features: [
      { label: "React / Next.js full-stack", dim: false },
      { label: "Database & auth (Supabase)", dim: false },
      { label: "Admin dashboard", dim: false },
      { label: "API integrations", dim: false },
      { label: "Deployment & hosting", dim: false },
      { label: "30-day support", dim: false },
    ],
    cta: "Book a Call",
    featured: false,
    delay: 3,
  },
];

export const automationTiers = [
  {
    tier: "Starter",
    name: "Quick Win",
    desc: "One workflow, one problem eliminated. I build and test a single automation that removes a repetitive task from your plate — permanently.",
    currency: "$",
    amount: "199",
    originalAmount: "249",
    period: "/ project",
    note: "One-time · Delivered in 3–5 days",
    features: [
      { label: "1 automated workflow (n8n, Zapier, or Make)", dim: false },
      { label: "Connects up to 3 apps", dim: false },
      { label: "Error alerts via email", dim: false },
      { label: "Fully documented workflow", dim: false },
      { label: "14-day bug fix support", dim: false },
      { label: "Ongoing maintenance", dim: true },
    ],
    cta: "Get a Quote",
    featured: false,
    delay: 1,
  },
  {
    tier: "Growth",
    name: "Workflow Stack",
    desc: "Up to 5 connected workflows replacing the manual glue between your tools. CRM, inbox, and Slack start talking to each other automatically.",
    currency: "$",
    amount: "599",
    originalAmount: "799",
    period: "/ project",
    note: "One-time · Delivered in 1–2 weeks",
    features: [
      { label: "Up to 5 automated workflows", dim: false },
      { label: "n8n or Make — your stack, your choice", dim: false },
      { label: "CRM, Slack, email & calendar integrations", dim: false },
      { label: "Error monitoring + auto-restart logic", dim: false },
      { label: "Handover documentation + walkthrough", dim: false },
      { label: "30-day support", dim: false },
    ],
    cta: "Get a Quote",
    featured: true,
    delay: 2,
  },
  {
    tier: "Custom",
    name: "AI Pipeline",
    desc: "Full automation architecture with AI at the center — lead bots, data pipelines, real-time triggers. Retainer option available.",
    currency: "$",
    amount: "1,200",
    originalAmount: null,
    period: "+ / project",
    note: "Custom quote · Retainer available",
    features: [
      { label: "Unlimited workflows & pipeline architecture", dim: false },
      { label: "OpenAI integration (chatbots, data processing)", dim: false },
      { label: "Webhook-driven real-time triggers", dim: false },
      { label: "Lead qualification or intake automation", dim: false },
      { label: "Monthly retainer option available", dim: false },
      { label: "Priority support + ongoing iterations", dim: false },
    ],
    cta: "Book a Call",
    featured: false,
    delay: 3,
  },
];
